config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'

  resources :recipes, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :unit, required: false
  belongs_to :recipe_version
  belongs_to :product

  delegate :name, to: :product
  alias_attribute :version, :recipe_version
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :ingredients
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  validates :name, presence: true
  has_many :recipe_versions

  def current_version
    versions.max_by(&:created_at)
  end

  def ingredients
    current_version.ingredients
  end

  alias latest_version current_version
  alias_attribute :versions, :recipe_versions
end

app/models/recipe_version.rb
class RecipeVersion < ApplicationRecord
  belongs_to :recipe
  has_many :ingredients
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :ingredients

  scope :imperial, -> { where(name: IMPERIAL_UNITS) }
  scope :metric, -> { where(name: METRIC_UNITS) }
  scope :volume, -> { where(name: VOLUME_UNITS) }

  IMPERIAL_UNITS = [
    'teaspoon',
    'tablespoon',
    'fluid ounce',
    'cup',
    'pint',
    'gallon',
    'pound',
    'ounce',
    'inch'
  ].freeze

  METRIC_UNITS = %w[
    milliliter
    liter
    milligram
    gram
    kilogram
    millimeter
    centimeter
    meter
  ].freeze

  VOLUME_UNITS = [
    'milliliter',
    'liter',
    'teaspoon',
    'tablespoon',
    'fluid ounce',
    'cup',
    'pint',
    'gallon'
  ].freeze

  def imperial?
    IMPERIAL_UNITS.include?(name)
  end

  def metric?
    METRIC_UNITS.include?(name)
  end

  def volume?
    VOLUME_UNITS.include?(name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_theme

  private

  def set_theme
    theme = params[:theme]
    return unless theme

    cookies[:theme] = theme.to_sym
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html

      format.json do
        render json: @recipes,
               adapter: :json,
               each_serializer: SimpleRecipeSerializer
      end
    end
  end

  def show
    @recipe = Recipe
      .includes(recipe_versions: { ingredients: %i[product unit] })
      .find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @recipe }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def switch_theme_path
    root_path(theme: cookies[:theme] == 'dark' ? 'light' : 'dark')
  end
end

app/views/application/_dark_mode_toggle.html.erb
<div>
  <label class='inline-flex relative items-center cursor-pointer'>
    <input type='checkbox'
           value=''
           class='sr-only peer'
           onchange="window.location.href='<%= switch_theme_path %>'"
           <%= cookies[:theme] == 'dark' ? 'checked' : '' %>>

    <div class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 dark:peer-focus:ring-blue-800 rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all dark:border-gray-600 peer-checked:bg-blue-600"></div>
    <span class='ml-3 text-sm font-medium text-gray-900 dark:text-gray-300'>Dark Mode</span>
  </label>
</div>

app/views/application/_table.html.erb
<table>
  <thead class='border-b border-slate-500'>
    <tr>
      <% columns.each do |column| %>
        <th class='py-4 text-left font-normal'><%= column %></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% rows.each do |row| %>
      <tr class='border-b border-slate-500 py-4 text-slate-500'>
        <%= yield row %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/application/_td.html.erb
<td class='py-4'>
  <%= yield %>
</td>

app/views/application/_title.html.erb
<h1 class='text-2xl'><%= text %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class='<%= cookies[:theme] %>'>
  <head>
    <title>recipe_repo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='dark:bg-slate-800 bg-white'>
    <main class='container mx-auto mt-3 md:mt-28 px-5 flex font-mono text-slate-900 dark:text-white flex flex-col'>
      <div class='flex flex-row justify-between mb-10'>
        <%= link_to root_path do %>
          recipe_repo
        <% end %>

        <%= render partial: 'dark_mode_toggle' %>
      </div>

      <%= yield %>
    </main>
  </body>
  </div>
</html>

app/views/recipes/index.html.erb
<%= render 'title', text: 'Recipes' %>

<%= render 'table', columns: ['Name'], rows: @recipes do |recipe| %>
  <%= render 'td' do %>
    <%= link_to recipe.name, recipe_path(recipe) %>
  <% end %>
<% end %>

app/views/recipes/show.html.erb
<%= render 'title', text: @recipe.name %>

<%= render 'table', columns: %w[Ingredients], rows: @recipe.ingredients do |ingredient| %>
  <% presenter = IngredientPresenter.new(ingredient) %>

  <%= render 'td' do %>
    <%= presenter.name_with_quantity %>
  <% end %>
<% end %>